- name: get_images
  uri:
    url: "https://api.serverspace.{{ sp_domain }}/api/v1/images"
    method: GET
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    status_code: 200
  register: images
  changed_when: 200
  delegate_to: localhost
  run_once: True

- debug:
    msg: "{{ images.json}}"
  run_once: True