# list all available regions and check APIs health
#- name: debug
#  debug:
#    msg: "{{ xapikey }}"

- name: vm_list
  uri:
    url: "https://api.serverspace.ru/api/v1/servers"
    method: GET
    headers:
      "x-api-key": "{{ xapikey }}"
    status_code: 200
  register: vm_list_result
  changed_when: 200
  delegate_to: localhost


- debug:
    msg: "{{ vm_list_result.json}}"
  run_once: True
