  - name: get_fingerprint_from_remote_host_fqdn
    shell: "ssh-keyscan -H -t rsa {{ fqdn }} >> ~/.ssh/known_hosts"
    register: result_of_adding_fingerprint
    delegate_to: localhost

  - name: set_user_password
    set_fact:
      user_password: "{{ root_password }}Hardening"

  - name: gather_facts_from_remote
    setup:

  - name: add_new_user_to_remote_host_etc_hosts
    shell: "useradd -m -d /home/hackatoner -p $(openssl passwd -1 {{ user_password }}) hackatoner"
    register: add_new_user_result

  - name: add_hackatoner_user_to_sudo_group
    command: "usermod -aG sudo hackatoner"
    register: add_to_sudo_group_result