---
- name: get_ssh_keys
  uri:
    url: "https://api.serverspace.{{ sp_domain }}/api/v1/ssh-keys"
    method: GET
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    status_code: 200
  register: ssh_keys
  changed_when: 200
  delegate_to: localhost
  run_once: True
  when: operation == "get"

- name: print_ssh_keys
  debug:
    msg: "{{ ssh_keys.json}}"
  run_once: True
  when: operation == "get"


- name: get_ssh_key_by_id
  uri:
    url: "https://api.serverspace.{{ sp_domain }}/api/v1/ssh-keys/{{ ssh_key_id }}"
    method: GET
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    status_code: 200
  register: ssh_key
  changed_when: 200
  delegate_to: localhost
  run_once: True
  when: operation == "get_by_id"

- name: print_ssh_key_by_id
  debug:
    msg: "{{ ssh_key.json }}"
  run_once: True
  when: operation == "get_by_id"

- name: add_ssh_key
  uri:
    url: "https://api.serverspace.{{ sp_domain }}/api/v1/ssh-keys"
    method: POST
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    body:
      name: "{{ ssh_key_name }}"
      public_key: "{{ public_key }}"
    status_code: 201
  register: ssh_key_add_result
  changed_when: 201
  delegate_to: localhost
  run_once: True
  when: operation == "create"

- name: print_id_of_added_key
  debug:
    msg: "{{ ssh_key_add_result.json }}"
  run_once: True
  when: operation == "create"


- name: delete_ssh_key
  uri:
    url: "https://api.serverspace.{{ sp_domain }}/api/v1/ssh-keys/{{ ssh_key_id }}"
    method: DELETE
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    status_code: 200
  register: ssh_key_delete_result
  changed_when: 200
  delegate_to: localhost
  run_once: True
  when: operation == "delete"

- name: print_of_deletion_result
  debug:
    msg: "{{ ssh_key_delete_result }}"
  run_once: True
  when: operation == "delete"