- name: get_project_details
  uri:
    url: "https://api.serverspace.{{ domain }}/api/v1/project"
    method: GET
    headers:
      "x-api-key": "{{ xapikey }}"
    body_format: json
    status_code: 200
  register: project
  changed_when: 200
  delegate_to: localhost
  run_once: True

- debug:
    msg: "{{ project.json}}"
  run_once: True